import { formatInrShort } from '../schemas/money.ts';

/*
 * Headlines are fixed sentence templates filled from the numbers, never an LLM (M12b: "Headlines
 * are generated by code, not an LLM"). `deltaPhrase` is the shared "up/down X% on <label>"
 * clause; AC7 covers its five cases: increase, decrease, no change, zero in the current
 * period (handled by the callers below, which skip the clause entirely when there is nothing
 * to compare), and no previous-period data.
 */

/** "up 18% on last month" / "the same as last month" / "no data for last month to compare". */
export function deltaPhrase(
  current: number,
  previous: number | null,
  previousLabel: string,
): string {
  if (previous === null) return `no data for ${previousLabel} to compare`;
  if (current === previous) return `the same as ${previousLabel}`;
  if (previous === 0) return `up from none in ${previousLabel}`;
  const pct = Math.round(Math.abs((current - previous) / previous) * 100);
  return `${current > previous ? 'up' : 'down'} ${pct}% on ${previousLabel}`;
}

/**
 * "124 enquiries this month, up 18% on last month." / "No enquiries this month." Zero in the
 * current period drops the comparison clause when there is nothing to compare it with either
 * (both zero still reads naturally via `deltaPhrase`'s "the same as" branch).
 */
export function countSentence(opts: {
  noun: string;
  pluralNoun: string;
  count: number;
  periodLabel: string;
  previous: number | null;
  previousLabel: string;
}): string {
  const { noun, pluralNoun, count, periodLabel, previous, previousLabel } = opts;
  if (count === 0 && previous === null) {
    return `No ${pluralNoun} ${periodLabel}.`;
  }
  const word = count === 1 ? noun : pluralNoun;
  const subject = count === 0 ? `No ${pluralNoun}` : `${count} ${word}`;
  return `${subject} ${periodLabel}, ${deltaPhrase(count, previous, previousLabel)}.`;
}

/** As `countSentence`, for an INR amount (M12b R6: "invoiced this period, change ..."). */
export function moneySentence(opts: {
  label: string;
  amountMinor: bigint;
  periodLabel: string;
  previousMinor: bigint | null;
  previousLabel: string;
}): string {
  const { label, amountMinor, periodLabel, previousMinor, previousLabel } = opts;
  const amountText = formatInrShort(amountMinor);
  if (amountMinor === 0n && previousMinor === null) {
    return `No ${label.toLowerCase()} ${periodLabel}.`;
  }
  // Percent comparisons never need bigint precision (display-only rounding).
  const current = Number(amountMinor);
  const previous = previousMinor === null ? null : Number(previousMinor);
  return `${label} ${amountText} ${periodLabel}, ${deltaPhrase(current, previous, previousLabel)}.`;
}

/** A share of a whole as a whole percentage, "31%"; "0%" for an empty whole. */
export function sharePct(part: bigint | number, whole: bigint | number): number {
  const p = typeof part === 'bigint' ? Number(part) : part;
  const w = typeof whole === 'bigint' ? Number(whole) : whole;
  return w > 0 ? Math.round((p / w) * 100) : 0;
}
